### ISSUE TITLE
Error with `ascii` codec during installation from sources

### ISSUE THREAD

**Issue by grandkarabas** [lrq3000/unireedsolomon#13]
Hello!

I have a problem during installation from [release sources v1.0.2](https://github.com/lrq3000/unireedsolomon/releases/download/v1.0.2/unireedsolomon-1.0.2.tar.gz). 

The error message is:
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-b74qszba/unireedsolomon/setup.py", line 51, in <module>
        long_description = open("README.rst", "r").read(),
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3471: ordinal not in range(128)
```

I found that **README.rst** contains the only utf-8 encoded symbol '–'. It is between `Reed` and `Solomon`:
```
* `<http://en.wikipedia.org/wiki/Reed–Solomon_error_correction>`_
```

Is it a typo or I should find another way to fix the problem?

Thank you in advance.

**Comment by lrq3000** [comment]
Should be fixed in the latest v1.0.6 release since we now use pyproject.toml and not anymore an open() call in setup.py. Thank you for opening this issue and sorry for the delay.
